"""All ORM models. Importing this package registers every mapper."""

from app.db.models.catalog import Country, Plan, PricingRule, Region, SupplierOffer
from app.db.models.content import (
    FAQ,
    Banner,
    Benefit,
    Device,
    PromoBanner,
    Testimonial,
)
from app.db.models.customers import Customer, Referral, SocialAccount
from app.db.models.enums import (
    DiscountType,
    ESIMStatus,
    ModerationStatus,
    OrderStatus,
    PaymentStatus,
    PlanScope,
    Provider,
    ReferralStatus,
)
from app.db.models.orders import (
    ESIM,
    AtmosTransaction,
    Order,
    OrderItem,
    Payment,
    PaymeTransaction,
    PromoCode,
    SupplierPurchase,
    TelegramRecipient,
)
from app.db.models.staff import (
    AccessFailureLog,
    AccessLog,
    CatalogSyncRun,
    ComplimentaryGrant,
    RowChange,
    Staff,
    TOTPDevice,
)
from app.db.models.support import SupportNote, SupportTicket

__all__ = [
    "ESIM",
    "FAQ",
    "AccessFailureLog",
    "AccessLog",
    "AtmosTransaction",
    "Banner",
    "Benefit",
    "CatalogSyncRun",
    "ComplimentaryGrant",
    "Country",
    "Customer",
    "Device",
    "DiscountType",
    "ESIMStatus",
    "ModerationStatus",
    "Order",
    "OrderItem",
    "OrderStatus",
    "PaymeTransaction",
    "Payment",
    "PaymentStatus",
    "Plan",
    "PlanScope",
    "PricingRule",
    "PromoBanner",
    "PromoCode",
    "Provider",
    "Referral",
    "ReferralStatus",
    "Region",
    "RowChange",
    "SocialAccount",
    "Staff",
    "SupplierOffer",
    "SupplierPurchase",
    "SupportNote",
    "SupportTicket",
    "TOTPDevice",
    "TelegramRecipient",
    "Testimonial",
]
