"""Bring two hand-made tables under version control.

Both of these exist in production and nowhere else, which is the problem.
`audit_row_change` and its triggers were created by hand in psql; the TOTP
device table arrived from a Django branch that was never merged. So the schema
CI tests against, the one a developer runs locally, and the one the service
actually meets in production were three different schemas — and the two
features that depend on them (the change journal and the backoffice's second
factor) could not be tested anywhere but production.

Everything here is IF NOT EXISTS. On production this revision changes nothing;
it simply records what is already there. On a fresh database it creates it.

Revision ID: 0003_audit_and_totp
Revises: 0002_support_tickets
"""

from __future__ import annotations

from alembic import op

revision: str = "0003_audit_and_totp"
down_revision: str | None = "0002_support_tickets"
branch_labels = None
depends_on = None

AUDITED_TABLES = ("orders_order", "orders_orderitem", "orders_payment")


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS audit_row_change (
            id          bigserial PRIMARY KEY,
            at          timestamptz NOT NULL DEFAULT now(),
            db_user     text NOT NULL DEFAULT SESSION_USER,
            app_name    text,
            client_addr inet,
            tbl         text NOT NULL,
            op          text NOT NULL,
            row_pk      text,
            old_row     jsonb,
            new_row     jsonb
        )
    """)
    # The trim job deletes by age, so that is the index it needs.
    op.execute("CREATE INDEX IF NOT EXISTS ix_audit_row_change_at ON audit_row_change (at)")

    # The trigger swallows its own errors on purpose: an audit row that cannot
    # be written must never roll back the sale it was recording.
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_row() RETURNS trigger
        LANGUAGE plpgsql AS $$
        begin
          begin
            insert into audit_row_change(app_name, client_addr, tbl, op, row_pk, old_row, new_row)
            values (
              nullif(current_setting('application_name', true), ''),
              inet_client_addr(),
              tg_table_name,
              tg_op,
              coalesce(to_jsonb(new)->>'id', to_jsonb(old)->>'id'),
              case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) end,
              case when tg_op in ('UPDATE','INSERT') then to_jsonb(new) end
            );
          exception when others then
            raise warning 'audit_row failed on % %: %', tg_table_name, tg_op, sqlerrm;
          end;
          return null;
        end
        $$
    """)
    for table in AUDITED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS zz_audit ON {table}")
        op.execute(f"""
            CREATE TRIGGER zz_audit AFTER INSERT OR UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION audit_row()
        """)

    # django-otp's table. The backoffice reads it to decide whether an account
    # needs a second factor; it is created here so that decision is testable
    # rather than something only production knows about.
    op.execute("""
        CREATE TABLE IF NOT EXISTS otp_totp_totpdevice (
            id                           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name                         varchar(64) NOT NULL DEFAULT '',
            confirmed                    boolean NOT NULL DEFAULT false,
            key                          varchar(80) NOT NULL,
            step                         smallint NOT NULL DEFAULT 30,
            digits                       smallint NOT NULL DEFAULT 6,
            tolerance                    smallint NOT NULL DEFAULT 1,
            drift                        smallint NOT NULL DEFAULT 0,
            last_t                       bigint NOT NULL DEFAULT -1,
            user_id                      integer NOT NULL
                                         REFERENCES auth_user(id) ON DELETE CASCADE,
            throttling_failure_count     integer NOT NULL DEFAULT 0,
            throttling_failure_timestamp timestamptz,
            created_at                   timestamptz,
            last_used_at                 timestamptz
        )
    """)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_otp_totp_totpdevice_user ON otp_totp_totpdevice (user_id)"
    )


def downgrade() -> None:
    # Only what this revision can have created on a fresh database. The audit
    # table is never dropped: it is the history, and a downgrade is not a
    # reason to lose it.
    op.execute("DROP TABLE IF EXISTS otp_totp_totpdevice")
